# Generated by Django 2.0.5 on 2018-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0009_auto_20180409_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='antibiotics',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=5, verbose_name='Since week two, were any of the following antibiotics given?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='blood_transfusions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Has the patient had any blood transfusions since week two? '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='blood_transfusions_units',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='If YES, no. of units?    '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='days_hospitalized',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Over the ten weeks spent in the study how many days did the patient spend in hospital?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='antibiotics',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=5, verbose_name='Since week two, were any of the following antibiotics given?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='blood_transfusions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Has the patient had any blood transfusions since week two? '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='blood_transfusions_units',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='If YES, no. of units?    '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='days_hospitalized',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Over the ten weeks spent in the study how many days did the patient spend in hospital?'),
            preserve_default=False,
        ),
    ]
