# Generated by Django 2.0.4 on 2018-06-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0011_auto_20180604_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='antibiotics',
        ),
        migrations.RemoveField(
            model_name='historicalfollowup',
            name='antibiotics',
        ),
        migrations.AddField(
            model_name='followup',
            name='antibiotic',
            field=models.ManyToManyField(blank=True, to='ambition_subject.Antibiotic', verbose_name='Were any of the following antibiotics given?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='antibiotic_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If other antibiotics, please specify:'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='antibiotic_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If other antibiotics, please specify:'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='blood_transfusions_units',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='If YES, no. of units?    '),
        ),
        migrations.AlterField(
            model_name='followup',
            name='days_hospitalized',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Over the ten weeks spent in the study how many days did the patient spend in hospital?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='blood_transfusions_units',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='If YES, no. of units?    '),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='days_hospitalized',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Over the ten weeks spent in the study how many days did the patient spend in hospital?'),
        ),
    ]
