# Generated by Django 2.0.4 on 2018-07-11 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0014_auto_20180622_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatienthistory',
            name='tablets_missed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='If not adherent, how many doses missed in the last month?'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='tablets_missed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='If not adherent, how many doses missed in the last month?'),
        ),
    ]
